### ISSUE TITLE
"Reader" error

### ISSUE THREAD

**Issue by LucasGood** [victoraalvarez/pythonPlayground#2]
When invoking forecastMap.py with `python forecastMap.py` I get the following error. The error message is admittedly unclear.

Traceback (most recent call last):
  File "forecastMap.py", line 35, in <module>
    reader = shpreader.Reader('./county_map/countyl010g.shp')
  File "/home/lucas/miniconda3/lib/python3.7/site-packages/cartopy/io/shapereader.py", line 206, in __init__
    self._reader = reader = shapefile.Reader(filename)
  File "/home/lucas/miniconda3/lib/python3.7/site-packages/shapefile.py", line 553, in __init__
    self.load(args[0])
  File "/home/lucas/miniconda3/lib/python3.7/site-packages/shapefile.py", line 646, in load
    raise ShapefileException("Unable to open %s.dbf or %s.shp." % (shapeName, shapeName))
shapefile.ShapefileException: Unable to open ./county_map/countyl010g.dbf or ./county_map/countyl010g.shp.

**Comment by victoraalvarez** [comment]
This is caused by the absolute path in the code; a directory that doesn't exist for you. Change it relative to yours.
